//
//  LoginScreenPresenter.swift
//  Interview
//
//  Created by Artur Michna on 18/10/2021.
//  Copyright (c) 2021 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenBusinessLogic { }

final class LoginScreenPresenter {
    weak var viewController: LoginScreenDisplayLogic?
}

extension LoginScreenPresenter: LoginScreenBusinessLogic { }
