//
//  LoginScreenViewController.swift
//  Interview
//
//  Created by Artur Michna on 18/10/2021.
//  Copyright (c) 2021 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SnapKit

protocol LoginScreenDisplayLogic: AnyObject { }

final class LoginScreenViewController: UIViewController {
    var presenter: LoginScreenBusinessLogic?
    var router: (NSObjectProtocol & LoginScreenRoutingLogic)?
    
    private lazy var loginButton: UIButton = {
        let button = UIButton()
        button.setTitle(NSLocalizedString("login_button", comment: ""), for: .normal)
        button.addTarget(self, action: #selector(didTapButton), for: .touchUpInside)
        button.layer.cornerRadius = 3.0
        button.backgroundColor = Colors().blueColor
        button.setTitleColor(Colors().textColor, for: .normal)
        return button
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        setUp()
    }
    
    @objc private func didTapButton() {
        
    }
    
    private func setUp() {
        view.addSubview(loginButton)
        loginButton.snp.makeConstraints { make in
            make.height.equalTo(40)
            make.width.equalTo(284)
            make.center.equalToSuperview()
        }
    }
}

extension LoginScreenViewController: LoginScreenDisplayLogic { }
