//
//  LoginScreenAssembly.swift
//  Interview
//
//  Created by Artur Michna on 18/10/2021.
//  Copyright (c) 2021 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import UIKit

final class LoginScreenAssembly {
    func createViewController() -> UIViewController {
        let viewController = LoginScreenViewController()
        let presenter = LoginScreenPresenter()
        let router = LoginScreenRouter()
        viewController.presenter = presenter
        viewController.router = router
        presenter.viewController = viewController
        router.viewController = viewController
        return viewController
    }
}
