//
//  CharacterScreenModels.swift
//  Interview
//
//  Created by Fandom on 28/10/2020.
//  Copyright (c) 2020 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//    Character screen should contain the following information:
//        character name
//        avatar
//        list of inventory items
//        each item should have a name colored based on rarity of the item
//        item type
//        information whether the item is magical or not below the name


import UIKit

enum CharacterScreen {
    
    struct ViewModel {
        let elements: [CellModel]
    }
    
    enum CellModel: Hashable {
        case equipment(item: EquipmentModel)
        case character(character: CharacterModel)
    }
    
    struct EquipmentModel: Hashable {
        let id: String
        let name: String
        let type: String
        let magic: Bool
        let color: UIColor?
    }
    
    struct CharacterModel: Hashable {
        let name: String
        let id: String
        let avatarURL: URL
    }
}

extension CharacterScreen.CellModel {
    var name: String {
        switch self {
        case .character(let character): return character.name
        case .equipment(let item): return item.name
        }
    }
}
