//
//  CharacterScreenWorker.swift
//  Interview
//
//  Created by Fandom on 28/10/2020.
//  Copyright (c) 2020 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class CharacterScreenWorker {
    private let httpClient: HTTPClient
    
    init(httpClient: HTTPClient) {
        self.httpClient = httpClient
    }
    
    func fetchData(completion: @escaping (Result<HTTPResponse, Error>) -> Void) {
        let request = URLRequest(.characterSheet)
        httpClient.httpTask(with: request) { result in
            completion(result)
        }.resume()
    }
}
