//
//  CharacterScreenModels.swift
//  Interview
//
//  Created by Fandom on 28/10/2020.
//  Copyright (c) 2020 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterScreen {
    // MARK: Use cases
    struct ViewModel {
        let elements: [CellModel]
    }
    
    enum CellModel: Hashable {
        case equipment(item: EquipmentModel)
        case character(character: CharacterModel)
    }
    
    struct EquipmentModel: Hashable {
        let name: String
    }
    
    struct CharacterModel: Hashable {
        let name: String
    }
}

extension CharacterScreen.CellModel {
    var name: String {
        switch self {
        case .character(let character): return character.name
        case .equipment(let item): return item.name
        }
    }
}
