//
//  CharacterScreenWorker.swift
//  Interview
//
//  Created by Fandom on 28/10/2020.
//  Copyright (c) 2020 Fandom. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


final class CharacterScreenWorker {
    private let httpClient: HTTPClient
    
    init(httpClient: HTTPClient) {
        self.httpClient = httpClient
    }
    
//    Character screen should contain the following information:
//        character name
//        avatar
//        list of inventory items
//        each item should have a name colored based on rarity of the item
//            Common - #F5F8FA
//            Uncommon - #5CBE3E
//            Rare - #5991DC
//            Very Rare - #B55DFF
//            Legendary - #F2A546
//            Artifact - #B78B76
//        item type
//        information whether the item is magical or not below the name
    
    func fetchData(completion: @escaping (Result<HTTPResponse, Error>) -> Void) {
        let request = URLRequest(.characterSheet)
        httpClient.httpTask(with: request) { result in
            completion(result)
        }.resume()
    }
}
